dist: ./dist
builds:
  - binary: fusion
    main: ./cmd/server
    env:
      # gcc-aarch64-linux-gnu is required
      # gcc-mingw-w64 are required for windows
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # TODO: gcc-mingw-w64 on linux-arm64 not includes aarch64-w64-mingw32-gcc
      - goos: windows
        goarch: arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      # - goos: windows
      #   goarch: arm64
      #   env:
      #     - CC=aarch64-w64-mingw32-gcc
      #     - CXX=aarch64-w64-mingw32-g++
      - goos: windows
        goarch: amd64
        goamd64: v1
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

archives:
  - id: default
    format: zip

checksum:
  algorithm: sha256
  name_template: "linux_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"
