dist: ./dist
builds:
  - binary: fusion
    main: ./cmd/server
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: zip

checksum:
  algorithm: sha256
  name_template: "darwin_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"
