# update with npx zeabur template update -f ./zeabur.yml -c 7FRK0K

apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Fusion RSS
spec:
  description: A lightweight RSS feed aggregator and reader
  icon: https://raw.githubusercontent.com/0x2E/fusion/refs/heads/main/frontend/static/icon-512.png
  coverImage: https://raw.githubusercontent.com/0x2E/fusion/refs/heads/main/assets/screenshot-light.png
  tags:
    - Tool
  readme: |-
    # Fusion
    A lightweight RSS feed aggregator and reader.
    Key features include:
    - Group, bookmark, search, automatic feed sniffing, OPML file import/export
    - Support for RSS, Atom, and JSON feed types
    - Responsive, light/dark mode, PWA, Keyboard shortcut support
    - Lightweight and self-hosted friendly
      - Built with Golang and SQLite, deploy with a single binary
      - Pre-built Docker image
      - Uses about 80MB of memory
    - Internationalization (i18n)
  variables:
    - key: PASSWORD
      type: STRING
      name: Password
      description: The password
    - key: PUBLIC_DOMAIN
      type: DOMAIN
      name: Domain
      description: What is the domain you want?
  services:
    - name: Fusion
      icon: https://raw.githubusercontent.com/0x2E/fusion/refs/heads/main/frontend/static/icon-512.png
      template: PREBUILT
      domainKey: PUBLIC_DOMAIN
      spec:
        source:
          image: ghcr.io/0x2e/fusion
        ports:
          - id: web
            port: 8080
            type: HTTP
        env:
          PASSWORD:
            default: ${PASSWORD}
        volumes:
          - id: data
            dir: /data
